console.log("Salam, Abubaker!") // Pakistani
console.log("Halo, Abubaker!") // Indonesian
console.log("Hola, Abubaker!") // Spanish
console.log("Hello, Abubaker!") // English
console.log("hallo, Abubaker!") // German
console.log("bonjour, Abubaker!") // French
console.log("أهلا, Abubaker!") // Arabic
console.log("नमस्ते, Abubaker!") // Hindi
console.log("হ্যালো, Abubaker!") // Bangaladeshi
console.log("привет, Abubaker!") // Russian
